Repository venpopov/bmm, pull requests merged in 2024-02, with the labels that each got.

#48 v0.1.1 - Generalize how model-specific arguments are provided
  DESCRIPTION
  NAMESPACE
  R/bmm-package.R
  R/bmm_model_2p.R
  R/bmm_model_3p.R
  R/bmm_model_IMM.R
  R/bmm_model_mixture2p.R
  R/bmm_model_mixture3p.R
  R/brms-misc.R
  R/calc_error_relative_to_nontargets.R
  R/configure-models.R
  R/distributions.R
  R/fit_model.R
  R/get_response.R
  R/helpers-data.R
  R/helpers-formula.R
  R/helpers-model.R
  R/helpers-parameters.R
  R/helpers-prior.R
  R/k2sd.R
  R/lsp.R
  R/model-helpers.R
  R/wrap.R
  README.Rmd
  README.md
  man/IMM.Rd
  man/SDM.Rd
  man/bmm-package.Rd
  man/c_parametrizations.Rd
  man/calc_error_relative_to_nontargets.Rd
  man/check_data.Rd
  man/configure_model.Rd
  man/figures/README-unnamed-chunk-4-1.png
  man/figures/README-unnamed-chunk-5-1.png
  man/fit_model.Rd
  man/get_response.Rd
  man/k2sd.Rd
  man/mixture2p.Rd
  man/mixture3p.Rd
  man/print_pretty_models_md.Rd
  man/supported_models.Rd
  man/use_model_template.Rd
  man/wrap.Rd
  tests/testthat/test-data-helpers.R
  tests/testthat/test-fit_model.R
  tests/testthat/test-helpers-data.R
  tests/testthat/test-helpers-model.R
  tests/testthat/test-wrap.R
Labels: enhancement

#93 Feature/issue 72 add check to sdm whether data is sorted by design matrix
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/bmm_model_sdmSimple.R
  R/brms-misc.R
  R/fit_model.R
  R/helpers-data.R
  R/helpers-formula.R
  R/utils.R
  man/fit_model.Rd
  tests/internal/internal-model-tests.Rmd
  tests/testthat/test-helpers-data.R
  tests/testthat/test-helpers-formula.R
Labels: enhancement

#121 Feature/issue 118 should we load brms automatically when bmm is loaded
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/utils.R
  man/save_pars.Rd
Labels: PR - patch

#122 Bigfix/issue 120 is data ordered fails with a complex formula
  DESCRIPTION
  NEWS.md
  R/helpers-data.R
  R/utils.R
  tests/testthat/test-helpers-data.R
Labels: PR - patch

#126 Documentation/116 change license to gpl-2
  DESCRIPTION
  LICENSE.md
  man/bmm-package.Rd
Labels: documentation, PR - patch

#137 Feature/117 add a message upon loading the package
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/fit_model.R
  R/utils.R
  R/zzz.R
  _pkgdown.yml
  man/bmm-package.Rd
  man/bmm_options.Rd
  man/fit_model.Rd
  tests/testthat/test-utils.R
Labels: documentation, PR - patch
